name: MinGW Windows ARM64 CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main ]

jobs:
  build-arm64:
    # Use GitHub's native Windows ARM64 runner
    runs-on: windows-11-arm

    defaults:
      run:
        # Force all workflow steps to run inside the MSYS2 bash environment
        shell: msys2 {0}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup MSYS2 and ARM64 Toolchain
        uses: msys2/setup-msys2@v2
        with:
          # Select the native Windows ARM64 environment
          msystem: CLANGARM64
          update: true
          # Install the necessary build tools and compilers
          install: >-
            mingw-w64-clang-aarch64-clang
            mingw-w64-clang-aarch64-toolchain
            git
            make
            cmake
            ninja
            mingw-w64-clang-aarch64-jansson
            mingw-w64-clang-aarch64-wxwidgets3.2-msw
            mingw-w64-clang-aarch64-lua
            mingw-w64-clang-aarch64-capstone
            mingw-w64-clang-aarch64-jbigkit
            mingw-w64-clang-aarch64-libbotan
            mingw-w64-clang-aarch64-libunistring


      - name: pacman extra packages
        run: |
          echo "mingw-w64-clang-aarch64-capstone has CVE-2025-68114, CVE-2025-67873"

      - name: Verify Compiler
        run: |
          clang --version
          gcc --version || true  # (Note: CLANGARM64 uses clang as the main driver)

      - name: Build Project
        run: |
          export CC=clang
          export CXX=clang++
          make -f Makefile.win

      # Recursive list using PowerShell (default shell on Windows runners)
      - name: List all files recursively (Bash)
        if: always()
        run: find .

      #debugging ci workflow
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          #name: testing-build       # The name of your downloadable zip file
          path: ./                  # The directory or file path to upload
          retention-days: 7            # Optional: How long to keep the files (Default: 90)
          if-no-files-found: error     # Optional: Fails the build if 'dist' is missing
